module.exports = {
  run: [
    // Step 1: Verify Docker is installed and running
    {
      method: "shell.run",
      params: {
        message: "node check-docker.js",
      },
    },

    // Step 2: Collect API keys from user
    {
      method: "input",
      params: {
        title: "OpenVoiceUI Setup",
        description: "Enter your AI provider API keys below. You need at least one AI provider key (Anthropic recommended) and a Groq key for voice synthesis.",
        form: [
          // --- AI Provider Keys (at least one needed) ---
          {
            key: "ANTHROPIC_API_KEY",
            title: "Anthropic API Key (recommended — default AI provider)",
            description: "console.anthropic.com/settings/keys",
            placeholder: "sk-ant-...",
            required: false,
          },
          {
            key: "OPENAI_API_KEY",
            title: "OpenAI API Key",
            description: "platform.openai.com/api-keys",
            placeholder: "sk-...",
            required: false,
          },
          {
            key: "GEMINI_API_KEY",
            title: "Google Gemini API Key (free tier available)",
            description: "aistudio.google.com/apikey",
            placeholder: "AIza...",
            required: false,
          },
          {
            key: "OPENROUTER_API_KEY",
            title: "OpenRouter API Key (access to 100+ models)",
            description: "openrouter.ai/keys",
            placeholder: "sk-or-...",
            required: false,
          },
          {
            key: "MISTRAL_API_KEY",
            title: "Mistral API Key",
            description: "console.mistral.ai/api-keys",
            placeholder: "",
            required: false,
          },
          {
            key: "XAI_API_KEY",
            title: "xAI API Key (Grok models)",
            description: "console.x.ai",
            placeholder: "xai-...",
            required: false,
          },
          // --- Required Keys ---
          {
            key: "GROQ_API_KEY",
            title: "Groq API Key (required — Text-to-Speech + fast LLM)",
            description: "Free tier at console.groq.com",
            placeholder: "gsk_...",
            required: true,
          },
          // --- Optional Settings ---
          {
            key: "PORT",
            title: "Port (default: 5001)",
            placeholder: "5001",
            required: false,
          },
        ],
      },
    },

    // Step 3: Create openclaw config directory
    {
      method: "shell.run",
      params: {
        message: "{{platform === 'win32' ? 'if not exist openclaw-data mkdir openclaw-data' : 'mkdir -p openclaw-data'}}",
      },
    },

    // Step 4: Write openclaw config (nested keys for v2026.3.2+)
    {
      method: "fs.write",
      params: {
        path: "openclaw-data/openclaw.json",
        text: JSON.stringify({
          gateway: {
            mode: "local",
            port: 18791,
            bind: "lan",
            auth: {
              token: "pinokio-local-token",
            },
            trustedProxies: ["127.0.0.1", "172.16.0.0/12", "10.0.0.0/8"],
            controlUi: {
              allowInsecureAuth: true,
              dangerouslyDisableDeviceAuth: true,
              allowedOrigins: [
                "http://localhost:18791",
                "http://127.0.0.1:18791",
                "http://localhost:5001",
                "http://127.0.0.1:5001",
              ],
            },
          },
          agents: {
            defaults: {
              thinkingDefault: "off",
              timeoutSeconds: 120,
            },
          },
        }, null, 2),
      },
    },

    // Step 5: Write .env with all provider keys
    {
      method: "fs.write",
      params: {
        path: ".env",
        text: [
          "# OpenVoiceUI — generated by Pinokio installer",
          "PORT={{input.PORT||5001}}",
          "DOMAIN=localhost",
          "SECRET_KEY=pinokio-local-install",
          "",
          "# OpenClaw Gateway",
          "CLAWDBOT_GATEWAY_URL=ws://127.0.0.1:18791",
          "CLAWDBOT_AUTH_TOKEN=pinokio-local-token",
          "GATEWAY_SESSION_KEY=voice-main-1",
          "",
          "# AI Provider Keys (openclaw uses whichever are set)",
          "ANTHROPIC_API_KEY={{input.ANTHROPIC_API_KEY}}",
          "OPENAI_API_KEY={{input.OPENAI_API_KEY}}",
          "GEMINI_API_KEY={{input.GEMINI_API_KEY}}",
          "OPENROUTER_API_KEY={{input.OPENROUTER_API_KEY}}",
          "MISTRAL_API_KEY={{input.MISTRAL_API_KEY}}",
          "XAI_API_KEY={{input.XAI_API_KEY}}",
          "",
          "# TTS — Groq (also available as fast LLM provider)",
          "GROQ_API_KEY={{input.GROQ_API_KEY}}",
          "USE_GROQ=true",
          "USE_GROQ_TTS=true",
          "",
          "# Supertonic TTS (ships with docker compose)",
          "SUPERTONIC_API_URL=http://supertonic:8765",
        ],
        join: "\n",
      },
    },

    // Step 6: Build Docker images (first run takes a few minutes)
    {
      method: "shell.run",
      params: {
        message: "docker compose -f docker-compose.yml -f docker-compose.pinokio.yml build",
      },
    },

    // Step 7: Done
    {
      method: "notify",
      params: {
        html: "OpenVoiceUI installed! Click <b>Start</b> to launch.<br><br>The app opens at <code>http://localhost:5001</code>.<br>To change your AI model or add more provider keys later, open <code>http://localhost:18791</code> (token: <code>pinokio-local-token</code>).",
      },
    },
  ],
}
