#!/usr/bin/env node
// setup-config.js — Generates all config files for OpenVoiceUI Pinokio install.
// Reads API keys from PINOKIO_* environment variables (set by install.js env: block).
// This avoids the broken json.set / pinokio-input.json flow entirely.

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function getKey(envName) {
  // install.js passes keys as PINOKIO_<KEY_NAME> via env
  const v = process.env["PINOKIO_" + envName] || "";
  if (!v || v === "undefined" || v === "null" || v.startsWith("{{")) return "";
  return v.trim();
}

const PORT = getKey("PORT") || "5001";
const token = crypto.randomBytes(24).toString("hex");
const secret = crypto.randomBytes(32).toString("hex");

// ---------------------------------------------------------------------------
// 1. Write openclaw.json (nested gateway/agents format for v2026.3.2+)
// ---------------------------------------------------------------------------

const openclawConfig = {
  gateway: {
    mode: "local",
    port: 18791,
    bind: "lan",
    auth: { mode: "token", token: token },
    trustedProxies: ["127.0.0.1", "172.16.0.0/12", "10.0.0.0/8"],
    controlUi: {
      allowInsecureAuth: true,
      dangerouslyDisableDeviceAuth: true,
    },
  },
  agents: {
    defaults: {
      thinkingDefault: "off",
      blockStreamingDefault: "on",
      blockStreamingBreak: "text_end",
      timeoutSeconds: 300,
    },
    list: [{ id: "main", default: true, workspace: "/root/.openclaw/workspace" }],
  },
};

fs.mkdirSync("openclaw-data/workspace", { recursive: true });
fs.writeFileSync(
  "openclaw-data/openclaw.json",
  JSON.stringify(openclawConfig, null, 2) + "\n"
);
console.log("  Wrote openclaw-data/openclaw.json");

// ---------------------------------------------------------------------------
// 2. Write .env
// ---------------------------------------------------------------------------

const envLines = [
  "# OpenVoiceUI — generated by Pinokio installer",
  `PORT=${PORT}`,
  "DOMAIN=localhost",
  `SECRET_KEY=${secret}`,
  "",
  "# OpenClaw Gateway",
  "CLAWDBOT_GATEWAY_URL=ws://127.0.0.1:18791",
  `CLAWDBOT_AUTH_TOKEN=${token}`,
  "GATEWAY_SESSION_KEY=voice-main-1",
  "",
  "# AI Provider Keys",
];

const envKeyList = [
  "ANTHROPIC_API_KEY", "OPENAI_API_KEY", "GEMINI_API_KEY",
  "OPENROUTER_API_KEY", "MISTRAL_API_KEY", "XAI_API_KEY", "ZAI_API_KEY",
  "CEREBRAS_API_KEY", "TOGETHER_API_KEY", "HF_TOKEN",
  "MOONSHOT_API_KEY", "KIMI_API_KEY", "MINIMAX_API_KEY", "QIANFAN_API_KEY",
  "MODELSTUDIO_API_KEY", "XIAOMI_API_KEY", "VOLCANO_ENGINE_API_KEY",
  "BYTEPLUS_API_KEY", "SYNTHETIC_API_KEY", "VENICE_API_KEY",
  "OPENCODE_ZEN_API_KEY", "KILOCODE_API_KEY", "AI_GATEWAY_API_KEY",
  "CLOUDFLARE_AI_GATEWAY_API_KEY", "LITELLM_API_KEY",
];
for (const k of envKeyList) envLines.push(`${k}=${getKey(k)}`);

envLines.push(
  "",
  "# TTS",
  `GROQ_API_KEY=${getKey("GROQ_API_KEY")}`,
  "USE_GROQ=true",
  "USE_GROQ_TTS=true",
  "",
  "# STT",
  `DEEPGRAM_API_KEY=${getKey("DEEPGRAM_API_KEY")}`,
  "",
  "# Supertonic TTS",
  "SUPERTONIC_API_URL=http://supertonic:8765"
);

fs.writeFileSync(".env", envLines.join("\n") + "\n");
console.log("  Wrote .env");

// ---------------------------------------------------------------------------
// 3. Write auth-profiles.json (so OpenClaw has working providers on first start)
// ---------------------------------------------------------------------------

const providerMap = {
  ANTHROPIC_API_KEY: "anthropic",
  OPENAI_API_KEY: "openai",
  GEMINI_API_KEY: "google",
  OPENROUTER_API_KEY: "openrouter",
  MISTRAL_API_KEY: "mistral",
  XAI_API_KEY: "xai",
  ZAI_API_KEY: "zai",
  CEREBRAS_API_KEY: "cerebras",
  TOGETHER_API_KEY: "together",
  HF_TOKEN: "huggingface",
  GROQ_API_KEY: "groq",
  DEEPGRAM_API_KEY: "deepgram",
  MOONSHOT_API_KEY: "moonshot",
  KIMI_API_KEY: "kimi-coding",
  MINIMAX_API_KEY: "minimax",
  QIANFAN_API_KEY: "qianfan",
  MODELSTUDIO_API_KEY: "modelstudio",
  XIAOMI_API_KEY: "xiaomi",
  VOLCANO_ENGINE_API_KEY: "volcano-engine",
  BYTEPLUS_API_KEY: "byteplus",
  SYNTHETIC_API_KEY: "synthetic",
  VENICE_API_KEY: "venice",
  OPENCODE_ZEN_API_KEY: "opencode",
  KILOCODE_API_KEY: "kilocode",
  AI_GATEWAY_API_KEY: "ai-gateway",
  CLOUDFLARE_AI_GATEWAY_API_KEY: "cloudflare-ai-gateway",
  LITELLM_API_KEY: "litellm",
};

const authProfiles = {};
let keyCount = 0;
for (const [envVar, providerId] of Object.entries(providerMap)) {
  const key = getKey(envVar);
  if (key) {
    authProfiles[providerId] = [
      {
        id: "default",
        type: "api_key",
        key,
        lastUsed: null,
        disabled: false,
        cooldown: null,
      },
    ];
    keyCount++;
  }
}

const agentDir = "openclaw-data/agents/main/agent";
fs.mkdirSync(agentDir, { recursive: true });
fs.writeFileSync(
  path.join(agentDir, "auth-profiles.json"),
  JSON.stringify(authProfiles, null, 2) + "\n"
);
console.log(`  Wrote auth-profiles.json (${keyCount} provider(s))`);

// ---------------------------------------------------------------------------
// Done
// ---------------------------------------------------------------------------

console.log("\n  Configuration complete!\n");
