// setup-config.js — Called by install.js via shell.run with env vars.
// Writes .env, openclaw.json, and auth-profiles.json from environment variables.
// This avoids Pinokio template resolution issues with fs.write.

const fs = require("fs");
const path = require("path");

// Filter out junk values from unresolved Pinokio templates or empty fields
function isRealValue(v) {
  if (!v || typeof v !== "string" || !v.trim()) return false;
  if (v === "undefined" || v === "null" || v.startsWith("{{")) return false;
  return true;
}

// --- 0. Load input from pinokio-input.json -----------------------------------
// Pinokio's {{input.*}} templates don't resolve in fs.write or shell.run env
// on Windows. We use json.set to write each key to a file, then read it here.

let input = {};
const inputFile = "pinokio-input.json";
try {
  input = JSON.parse(fs.readFileSync(inputFile, "utf8"));
  console.log(`  Read ${Object.keys(input).length} keys from ${inputFile}`);
} catch (e) {
  console.error(`  ERROR: Could not read ${inputFile}: ${e.message}`);
  console.error("  The install form may not have saved properly. Try Reinstall.");
  process.exit(1);
}

// Helper: get a value from input JSON, falling back to env var
function getKey(name) {
  const fromJson = input[name];
  if (isRealValue(fromJson)) return fromJson.trim();
  const fromEnv = process.env[name];
  if (isRealValue(fromEnv)) return fromEnv.trim();
  return "";
}

const PORT = getKey("PORT") || "5001";

// --- Validate required keys --------------------------------------------------

const hasGroq = !!getKey("GROQ_API_KEY");
const hasDeepgram = !!getKey("DEEPGRAM_API_KEY");
const aiProviderKeys = ["ANTHROPIC_API_KEY", "ZAI_API_KEY", "OPENAI_API_KEY"];
const hasAiProvider = aiProviderKeys.some(k => !!getKey(k));

if (!hasGroq || !hasDeepgram || !hasAiProvider) {
  console.error("\n  ============================================================");
  console.error("  INSTALL FAILED — Missing required API keys\n");
  if (!hasGroq) console.error("    MISSING: Groq API Key (required for Text-to-Speech)");
  if (!hasDeepgram) console.error("    MISSING: Deepgram API Key (required for Speech-to-Text)");
  if (!hasAiProvider) console.error("    MISSING: At least one AI provider key (Anthropic, Z.AI, or OpenAI)");
  console.error("\n  Click Reinstall and fill in the required fields.");
  console.error("  ============================================================\n");
  process.exit(1);
}

// --- 1. Write .env -----------------------------------------------------------

const envLines = [
  "# OpenVoiceUI — generated by Pinokio installer",
  `PORT=${PORT}`,
  "DOMAIN=localhost",
  "SECRET_KEY=pinokio-local-install",
  "",
  "# OpenClaw Gateway",
  "CLAWDBOT_GATEWAY_URL=ws://127.0.0.1:18791",
  "CLAWDBOT_AUTH_TOKEN=pinokio-local-token",
  "GATEWAY_SESSION_KEY=voice-main-1",
  "",
  "# AI Provider Keys (openclaw uses whichever are set)",
];

// Every env-var → .env key mapping (only write non-empty values)
const envKeys = [
  "ANTHROPIC_API_KEY", "OPENAI_API_KEY", "GEMINI_API_KEY",
  "OPENROUTER_API_KEY", "MISTRAL_API_KEY", "XAI_API_KEY", "ZAI_API_KEY",
  "CEREBRAS_API_KEY", "TOGETHER_API_KEY", "HF_TOKEN",
  "MOONSHOT_API_KEY", "KIMI_API_KEY", "MINIMAX_API_KEY", "QIANFAN_API_KEY",
  "MODELSTUDIO_API_KEY", "XIAOMI_API_KEY", "VOLCANO_ENGINE_API_KEY",
  "BYTEPLUS_API_KEY", "SYNTHETIC_API_KEY", "VENICE_API_KEY",
  "OPENCODE_ZEN_API_KEY", "KILOCODE_API_KEY", "AI_GATEWAY_API_KEY",
  "CLOUDFLARE_AI_GATEWAY_API_KEY", "LITELLM_API_KEY",
];

for (const k of envKeys) {
  envLines.push(`${k}=${getKey(k)}`);
}

envLines.push(
  "",
  "# TTS — Groq (also available as fast LLM provider)",
  `GROQ_API_KEY=${getKey("GROQ_API_KEY")}`,
  "USE_GROQ=true",
  "USE_GROQ_TTS=true",
  "",
  "",
  "# STT — Deepgram (Speech-to-Text)",
  `DEEPGRAM_API_KEY=${getKey("DEEPGRAM_API_KEY")}`,
  "",
  "# Supertonic TTS (ships with docker compose)",
  "SUPERTONIC_API_URL=http://supertonic:8765",
);

fs.writeFileSync(".env", envLines.join("\n") + "\n");
console.log("  Wrote .env");

// --- 2. Write openclaw.json --------------------------------------------------

const openclawConfig = {
  gateway: {
    mode: "local",
    port: 18791,
    auth: {
      mode: "token",
      token: "pinokio-local-token",
    },
    trustedProxies: ["127.0.0.1", "172.16.0.0/12", "10.0.0.0/8"],
    controlUi: {
      allowInsecureAuth: true,
      dangerouslyDisableDeviceAuth: true,
      dangerouslyAllowHostHeaderOriginFallback: true,
    },
  },
  agents: {
    defaults: {
      thinkingDefault: "off",
      blockStreamingDefault: "on",
      blockStreamingBreak: "text_end",
      timeoutSeconds: 300,
    },
    list: [
      {
        id: "main",
        default: true,
        workspace: "/root/.openclaw/workspace",
      },
    ],
  },
};

fs.mkdirSync("openclaw-data/workspace", { recursive: true });
fs.writeFileSync(
  "openclaw-data/openclaw.json",
  JSON.stringify(openclawConfig, null, 2) + "\n"
);
console.log("  Wrote openclaw-data/openclaw.json");

// --- 3. Write auth-profiles.json ---------------------------------------------
// OpenClaw reads API keys from agents/<id>/agent/auth-profiles.json, NOT from
// environment variables. Without this file, every LLM request fails with
// "No API key found for provider".

// Map: env-var name → openclaw provider ID
const providerMap = {
  ANTHROPIC_API_KEY:               "anthropic",
  OPENAI_API_KEY:                  "openai",
  GEMINI_API_KEY:                  "google",
  OPENROUTER_API_KEY:              "openrouter",
  MISTRAL_API_KEY:                 "mistral",
  XAI_API_KEY:                     "xai",
  ZAI_API_KEY:                     "zai",
  CEREBRAS_API_KEY:                "cerebras",
  TOGETHER_API_KEY:                "together",
  HF_TOKEN:                        "huggingface",
  GROQ_API_KEY:                    "groq",
  DEEPGRAM_API_KEY:                "deepgram",
  MOONSHOT_API_KEY:                "moonshot",
  KIMI_API_KEY:                    "kimi-coding",
  MINIMAX_API_KEY:                 "minimax",
  QIANFAN_API_KEY:                 "qianfan",
  MODELSTUDIO_API_KEY:             "modelstudio",
  XIAOMI_API_KEY:                  "xiaomi",
  VOLCANO_ENGINE_API_KEY:          "volcano-engine",
  BYTEPLUS_API_KEY:                "byteplus",
  SYNTHETIC_API_KEY:               "synthetic",
  VENICE_API_KEY:                  "venice",
  OPENCODE_ZEN_API_KEY:            "opencode",
  KILOCODE_API_KEY:                "kilocode",
  AI_GATEWAY_API_KEY:              "ai-gateway",
  CLOUDFLARE_AI_GATEWAY_API_KEY:   "cloudflare-ai-gateway",
  LITELLM_API_KEY:                 "litellm",
};

const authProfiles = {};
let keyCount = 0;

for (const [envVar, providerId] of Object.entries(providerMap)) {
  const key = getKey(envVar);
  if (key) {
    authProfiles[providerId] = [
      {
        id: "default",
        type: "api_key",
        key: key,
        lastUsed: null,
        disabled: false,
        cooldown: null,
      },
    ];
    keyCount++;
  }
}

// Create agent directory and write auth-profiles
const agentDir = "openclaw-data/agents/main/agent";
fs.mkdirSync(agentDir, { recursive: true });
fs.writeFileSync(
  path.join(agentDir, "auth-profiles.json"),
  JSON.stringify(authProfiles, null, 2) + "\n"
);
console.log(`  Wrote auth-profiles.json (${keyCount} provider(s) configured)`);

if (keyCount === 0) {
  console.warn("\n  WARNING: No AI provider keys were entered!");
  console.warn("  The agent won't be able to respond without at least one key.");
  console.warn("  Re-run the installer to add keys, or edit openclaw-data/agents/main/agent/auth-profiles.json\n");
}

console.log("\n  Configuration complete!\n");
