#!/bin/bash
set -e

# =========================================
# Client Dashboard Canvas Plugin Installer
# =========================================
# Usage: ./install.sh <user> <volume_id> <openvoiceui_port>
# Example: ./install.sh foamology HC_Volume_104807901 15009

USER=${1:-}
VOLUME_ID=${2:-}
OV_PORT=${3:-}

if [ -z "$USER" ] || [ -z "$VOLUME_ID" ] || [ -z "$OV_PORT" ]; then
  echo "Usage: $0 <user> <volume_id> <openvoiceui_port>"
  echo "Example: $0 foamology HC_Volume_104807901 15009"
  exit 1
fi

VOLUME="/mnt/$VOLUME_ID"
API_PORT=$((16300 + ${OV_PORT: -1}))
PLUGIN_DIR="$(cd "$(dirname "$0")" && pwd)"
CANVAS_DIR="${VOLUME}/canvas-pages"
OV_DIR="${VOLUME}/${USER}/ai/OpenVoiceUI-public"

echo "=== Installing Client Dashboard Plugin ==="
echo "User: $USER"
echo "Volume: $VOLUME"
echo "OpenVoiceUI Port: $OV_PORT"
echo "API Port: $API_PORT"
echo "Plugin Dir: $PLUGIN_DIR"
echo "Canvas Dir: $CANVAS_DIR"
echo ""

# 1. Ensure canvas pages directory exists
echo "[1/8] Creating canvas pages directory..."
sudo mkdir -p "$CANVAS_DIR"
sudo chown "$USER:$USER" "$CANVAS_DIR"

# 2. Copy canvas pages
echo "[2/8] Installing canvas pages..."
for page in "$PLUGIN_DIR"/pages/*.html; do
  cp "$page" "$CANVAS_DIR/"
  echo "  - $(basename $page)"
done

# 3. Copy shared assets
echo "[3/8] Installing shared assets..."
cp "$PLUGIN_DIR/assets/dashboard.css" "$CANVAS_DIR/"
cp "$PLUGIN_DIR/assets/dashboard.js" "$CANVAS_DIR/"
echo "  - dashboard.css"
echo "  - dashboard.js"

# 4. Install API server
echo "[4/8] Installing API server..."
API_DIR="${OV_DIR}/canvas-plugins/client-dashboard/api"
mkdir -p "$API_DIR"
cp -r "$PLUGIN_DIR/api"/* "$API_DIR/"
echo "  - API files copied"

# 5. Install npm dependencies
echo "[5/8] Installing npm dependencies..."
cd "$API_DIR" && npm install --production 2>&1 | tail -5

# 6. Create .env for API
echo "[6/8] Creating API configuration..."
# Read from OpenVoiceUI .env for shared values
OV_ENV="${OV_DIR}/.env"

# Extract DATABASE_URL if available
DATABASE_URL=$(grep -E "^DATABASE_URL=" "$OV_ENV" 2>/dev/null | cut -d= -f2- || echo "")

cat > "$API_DIR/.env" << EOF
# Dashboard API Configuration
# Generated by install.sh for $USER

# Server
PORT=$API_PORT

# Database (from OpenVoiceUI)
DATABASE_URL=$DATABASE_URL

# AI (Google Gemini) - set these manually
GEMINI_API_KEY=
# GEMINI_API_KEY=your-gemini-api-key

# Social Media (OneUp) - set these manually
ONEUP_API_KEY=
# ONEUP_API_KEY=your-oneup-api-key

# Image Storage (GitHub) - set these manually
GITHUB_TOKEN=
GITHUB_REPO=${USER}-social-images
GITHUB_BRANCH=main

# Filesystem
WEBSITES_DIR=${VOLUME}/websites

# Multi-tenant
TENANT_ID=${USER}
EOF

echo "  - .env created at $API_DIR/.env"
echo "  - NOTE: You need to set GEMINI_API_KEY and ONEUP_API_KEY manually!"

# 7. Update OpenVoiceUI .env
echo "[7/8] Configuring OpenVoiceUI..."
if ! grep -q "DASHBOARD_API_PORT" "$OV_ENV"; then
  echo "" >> "$OV_ENV"
  echo "# Dashboard API (canvas plugin)" >> "$OV_ENV"
  echo "DASHBOARD_API_PORT=$API_PORT" >> "$OV_ENV"
  echo "  - Added DASHBOARD_API_PORT=$API_PORT"
else
  sed -i "s/DASHBOARD_API_PORT=.*/DASHBOARD_API_PORT=$API_PORT/" "$OV_ENV"
  echo "  - Updated DASHBOARD_API_PORT=$API_PORT"
fi

# 8. Create systemd service
echo "[8/8] Creating systemd service..."
sudo tee /etc/systemd/system/dashboard-api-${USER}.service > /dev/null << EOF
[Unit]
Description=Dashboard API Server ($USER)
After=network.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$API_DIR
EnvironmentFile=$API_DIR/.env
ExecStart=/usr/bin/node server.js
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable dashboard-api-${USER}
echo "  - Service created: dashboard-api-${USER}.service"

echo ""
echo "=== Installation Complete ==="
echo ""
echo "Configuration file: $API_DIR/.env"
echo "  --> EDIT THIS FILE to add your API keys:"
echo "      - GEMINI_API_KEY (for AI content generation)"
echo "      - ONEUP_API_KEY (for social media publishing)"
echo ""
echo "Start API server:"
echo "  sudo systemctl start dashboard-api-${USER}"
echo ""
echo "View logs:"
echo "  sudo journalctl -u dashboard-api-${USER} -f"
echo ""
echo "Canvas pages installed in: $CANVAS_DIR"
echo ""
echo "Voice commands:"
echo "  - 'Show dashboard' → opens main dashboard"
echo "  - 'Show posts' → opens post approvals"
echo "  - 'Show schedule' → opens calendar"
echo "  - 'Show content' → opens content library"
echo ""
echo "API endpoints available at: http://localhost:$API_PORT"
