"""
routes/airadio_bridge.py — AI-Radio Bridge Blueprint

Bridges OpenVoiceUI to the per-VPS AI-Radio service (Next.js, on the
shared `jambot-shared` Docker network at http://ai-radio:3000).

All endpoints are prefixed `/api/airadio/`. Frontend voice-tag parser
and canvas pages call these routes; the Flask app then proxies to the
scoped AI-Radio "agent API" at `${AIRADIO_URL}/api/agent/*`, signing
every outbound request with `X-JamBot-Agent-Key` + `X-JamBot-User`.

Spec: /mnt/system/base/airadio/docs/PLAN/18-OVU-INTEGRATION.md

Endpoints registered:
  POST  /api/airadio/push-song
  POST  /api/airadio/push-playlist
  POST  /api/airadio/set-image
  GET   /api/airadio/resolve
  POST  /api/airadio/play
  GET   /api/airadio/inbox
  POST  /api/airadio/send-to-friend
  POST  /api/airadio/vote
  POST  /api/airadio/friend-request
  POST  /api/airadio/friend-accept
  POST  /api/airadio/friend-decline
  GET   /api/airadio/library
"""

import logging
import mimetypes
import os
from pathlib import Path

import requests as http_requests
from flask import Blueprint, jsonify, request

from services.paths import (
    GENERATED_MUSIC_DIR,
    KNOWN_FACES_DIR,
    MUSIC_DIR,
    RUNTIME_DIR,
    UPLOADS_DIR,
)
from routes.music import (
    load_generated_music_metadata,
    load_music_metadata,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Configuration (env at module load)
# ---------------------------------------------------------------------------

AIRADIO_URL = os.environ.get("AIRADIO_URL", "http://ai-radio:3000").rstrip("/")
# Per-user key (aia_sk_*) takes precedence over the platform-shared agent key
# when set. Generated by the user at ai-radio.jam-bot.com/settings.
AIRADIO_USER_KEY = os.environ.get("AIRADIO_USER_KEY", "")
AIRADIO_AGENT_KEY = os.environ.get("AIRADIO_AGENT_KEY", "")
AIRADIO_JAMBOT_USER = os.environ.get("AIRADIO_JAMBOT_USER", "")
AIRADIO_TIMEOUT = int(os.environ.get("AIRADIO_TIMEOUT", "30"))

# ---------------------------------------------------------------------------
# Whitelisted local directories for set-image (security: NO arbitrary paths)
# ---------------------------------------------------------------------------

# Paths the agent is allowed to upload from. Anything outside these is rejected.
# Mirrors the rule in PLAN/18-OVU-INTEGRATION.md §3.3.
_FACES_DIR = RUNTIME_DIR / "faces"
_TEMP_DIR = RUNTIME_DIR / "1temp"

_IMAGE_WHITELIST_DIRS = [
    UPLOADS_DIR.resolve(),
    _FACES_DIR.resolve(),
    KNOWN_FACES_DIR.resolve(),
    GENERATED_MUSIC_DIR.resolve(),
    _TEMP_DIR.resolve(),
]

# URL-prefix → on-disk dir map for paths like "/uploads/foo.png"
_URL_PREFIX_MAP = {
    "/uploads/": UPLOADS_DIR,
    "/faces/": _FACES_DIR,
    "/known_faces/": KNOWN_FACES_DIR,
    "/generated_music/": GENERATED_MUSIC_DIR,
    "/1temp/": _TEMP_DIR,
}

# ---------------------------------------------------------------------------
# Blueprint
# ---------------------------------------------------------------------------

airadio_bp = Blueprint("airadio", __name__)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _bridge_configured() -> bool:
    """True iff URL is set AND at least one auth mechanism is available."""
    return bool(AIRADIO_URL) and bool(AIRADIO_USER_KEY or AIRADIO_AGENT_KEY)


def _bridge_not_configured_response():
    """Standard 503 returned when env vars are missing."""
    missing = []
    if not AIRADIO_URL:
        missing.append("AIRADIO_URL")
    if not AIRADIO_USER_KEY and not AIRADIO_AGENT_KEY:
        missing.append("AIRADIO_USER_KEY (or legacy AIRADIO_AGENT_KEY + AIRADIO_JAMBOT_USER)")
    msg = (
        "AI-Radio bridge is not configured. "
        f"Missing env: {', '.join(missing) or 'unknown'}"
    )
    return (
        jsonify({
            "ok": False,
            "error": {"code": "BRIDGE_NOT_CONFIGURED", "message": msg},
        }),
        503,
    )


def _agent_headers() -> dict:
    """
    Auth headers attached to every outbound AI-Radio call.

    Preferred path: Authorization: Bearer aia_sk_* (per-user key from the
    AI-Radio settings page). Identity is embedded in the key.

    Legacy fallback: X-JamBot-Agent-Key + X-JamBot-User (platform-shared
    secret + subdomain-as-user). Retained so existing clients keep working
    during migration.
    """
    if AIRADIO_USER_KEY:
        return {"Authorization": f"Bearer {AIRADIO_USER_KEY}"}
    return {
        "X-JamBot-Agent-Key": AIRADIO_AGENT_KEY,
        "X-JamBot-User": AIRADIO_JAMBOT_USER,
    }


def _airadio_call(method, path, json=None, files=None, params=None, data=None):
    """
    Wrapper around `requests` that targets AI-Radio with the auth headers.

    Returns a dict shaped:
        {"ok": bool, "data": <json or None>, "error": <dict or None>, "status": int}

    On non-2xx responses we propagate the AI-Radio error body if it parses as
    JSON, otherwise wrap a synthesized error.
    """
    url = f"{AIRADIO_URL}{path}"
    headers = _agent_headers()
    try:
        print(f"📻 AI-Radio {method} {path}")
        resp = http_requests.request(
            method,
            url,
            headers=headers,
            json=json,
            files=files,
            params=params,
            data=data,
            timeout=AIRADIO_TIMEOUT,
        )
    except http_requests.Timeout as exc:
        logger.warning("AI-Radio timeout: %s %s — %s", method, path, exc)
        return {
            "ok": False,
            "data": None,
            "status": 504,
            "error": {
                "code": "BRIDGE_TIMEOUT",
                "message": f"AI-Radio timed out after {AIRADIO_TIMEOUT}s",
            },
        }
    except http_requests.RequestException as exc:
        logger.warning("AI-Radio request failed: %s %s — %s", method, path, exc)
        return {
            "ok": False,
            "data": None,
            "status": 502,
            "error": {
                "code": "BRIDGE_UNREACHABLE",
                "message": f"Could not reach AI-Radio: {exc}",
            },
        }

    # Try to parse a JSON body — AI-Radio always returns JSON per its contract.
    try:
        body = resp.json()
    except ValueError:
        body = None

    if 200 <= resp.status_code < 300:
        # AI-Radio's own contract is { ok, data?, error? }. Pass it through if
        # present; otherwise treat the parsed body as `data`.
        if isinstance(body, dict) and "ok" in body:
            return {
                "ok": bool(body.get("ok")),
                "data": body.get("data"),
                "error": body.get("error"),
                "status": resp.status_code,
            }
        return {"ok": True, "data": body, "error": None, "status": resp.status_code}

    # Non-2xx — propagate AI-Radio's error if it gave us one.
    if isinstance(body, dict) and body.get("error"):
        return {
            "ok": False,
            "data": body.get("data"),
            "error": body.get("error"),
            "status": resp.status_code,
        }
    return {
        "ok": False,
        "data": None,
        "status": resp.status_code,
        "error": {
            "code": "AIRADIO_HTTP_ERROR",
            "message": f"AI-Radio returned HTTP {resp.status_code}",
            "body": (resp.text or "")[:400],
        },
    }


def _bridge_response(result):
    """Convert an `_airadio_call` result into a Flask (json, status) tuple."""
    payload = {"ok": result["ok"], "data": result.get("data"), "error": result.get("error")}
    # Preserve AI-Radio's status code for non-success cases; otherwise 200.
    status = 200 if result["ok"] else (result.get("status") or 502)
    return jsonify(payload), status


def _resolve_local_song(filename: str, playlist: str):
    """
    Look up a local audio track by filename in either the library or the
    generated playlist. Returns (Path, metadata_dict) or (None, None) if
    not found / playlist invalid / path-traversal attempt.
    """
    if not filename:
        return None, None
    if playlist == "generated":
        base_dir = GENERATED_MUSIC_DIR
        meta = load_generated_music_metadata()
    elif playlist == "library":
        base_dir = MUSIC_DIR
        meta = load_music_metadata()
    else:
        return None, None

    # Strict containment — reject `..`, absolute paths, anything not in base.
    safe_name = Path(filename).name
    if safe_name != filename:
        return None, None

    candidate = (base_dir / safe_name).resolve()
    try:
        candidate.relative_to(base_dir.resolve())
    except ValueError:
        return None, None
    if not candidate.is_file():
        return None, None
    return candidate, meta.get(safe_name, {})


def _resolve_image_path(raw_path: str):
    """
    Map a user-supplied image path (URL-style like `/uploads/foo.png` or a
    bare filename) to an absolute Path inside one of the whitelisted dirs.

    Returns Path on success, None on rejection. Strict — no `..`, no absolute
    paths outside the whitelist.
    """
    if not raw_path or not isinstance(raw_path, str):
        return None

    # Reject anything containing `..` outright before anything else.
    if ".." in raw_path:
        return None

    # Reject absolute paths that aren't already inside a whitelisted dir.
    candidate = None
    if raw_path.startswith("/"):
        # First, try matching a known URL prefix.
        for prefix, base in _URL_PREFIX_MAP.items():
            if raw_path.startswith(prefix):
                relative = raw_path[len(prefix):]
                if "/" in relative or "\\" in relative:
                    # No nested subdirs allowed (matches existing /uploads style).
                    return None
                candidate = (base / relative).resolve()
                break
        if candidate is None:
            # An absolute path that doesn't begin with one of our prefixes is
            # never accepted — that would let the agent reach into the host FS.
            return None
    else:
        # Bare filename — assume uploads/ by convention.
        if "/" in raw_path or "\\" in raw_path:
            return None
        candidate = (UPLOADS_DIR / raw_path).resolve()

    if not candidate.is_file():
        return None

    # Final containment check against the whitelist.
    for allowed in _IMAGE_WHITELIST_DIRS:
        try:
            candidate.relative_to(allowed)
            return candidate
        except ValueError:
            continue
    return None


def _stream_song(local_path: Path, fields: dict):
    """
    POST a song file to AI-Radio's /api/agent/push-song as multipart/form-data.

    `fields` is a dict of metadata fields (title, source, etc.) that travel
    alongside the audio bytes. AI-Radio dedupes via the `sourceHash` it
    computes server-side.
    """
    mime, _ = mimetypes.guess_type(str(local_path))
    if not mime:
        mime = "audio/mpeg"
    with open(local_path, "rb") as fh:
        files = {"file": (local_path.name, fh, mime)}
        return _airadio_call(
            "POST",
            "/api/agent/push-song",
            files=files,
            data=fields or None,
        )


def _stream_image(local_path: Path, fields: dict):
    """POST an image file to AI-Radio's /api/agent/set-image."""
    mime, _ = mimetypes.guess_type(str(local_path))
    if not mime:
        mime = "application/octet-stream"
    with open(local_path, "rb") as fh:
        files = {"file": (local_path.name, fh, mime)}
        return _airadio_call(
            "POST",
            "/api/agent/set-image",
            files=files,
            data=fields or None,
        )


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@airadio_bp.route("/api/airadio/push-song", methods=["POST"])
def push_song():
    """
    Push a single song from MUSIC_DIR (library) or GENERATED_MUSIC_DIR
    (generated) to AI-Radio.

    Body: { "filename": "...", "playlist": "library"|"generated",
            "title": optional, "cover_path": optional local image path }
    """
    if not _bridge_configured():
        return _bridge_not_configured_response()

    body = request.get_json(silent=True) or {}
    filename = body.get("filename")
    playlist = body.get("playlist", "library")
    title = body.get("title")
    cover_path = body.get("cover_path")

    local_path, meta = _resolve_local_song(filename, playlist)
    if local_path is None:
        return jsonify({
            "ok": False,
            "error": {
                "code": "NOT_FOUND",
                "message": f"Song '{filename}' not found in '{playlist}' playlist",
            },
        }), 404

    fields = {
        "title": title or (meta or {}).get("title") or local_path.stem,
        "source": "ovu-library" if playlist == "library" else "ovu-generated",
        "playlist": playlist,
    }
    # Carry through any useful metadata so AI-Radio doesn't lose it.
    for src_key, dst_key in (
        ("artist", "artist"),
        ("genre", "genre"),
        ("description", "description"),
        ("duration_seconds", "duration"),
        ("suno_id", "sunoId"),
    ):
        if meta and meta.get(src_key) is not None:
            fields[dst_key] = str(meta[src_key])

    print(f"📻 push-song: {local_path.name} → AI-Radio (playlist={playlist})")
    result = _stream_song(local_path, fields)
    if not result["ok"]:
        return _bridge_response(result)

    # Normalize success shape: { ok, songId, url } as the spec requires,
    # while still passing through anything else AI-Radio gave us.
    data = result.get("data") or {}
    out = {
        "ok": True,
        "songId": data.get("songId") or data.get("id"),
        "url": data.get("url"),
        "data": data,
    }
    return jsonify(out), 200


@airadio_bp.route("/api/airadio/push-playlist", methods=["POST"])
def push_playlist():
    """
    Push a whole playlist to AI-Radio (inline mode — one song per request).

    Body: { "name": "...", "playlist": "library"|"generated",
            "description": optional }
    """
    if not _bridge_configured():
        return _bridge_not_configured_response()

    body = request.get_json(silent=True) or {}
    name = body.get("name")
    playlist = body.get("playlist", "library")
    description = body.get("description", "")

    if not name:
        return jsonify({
            "ok": False,
            "error": {"code": "VALIDATION_FAILED", "message": "Missing 'name' field"},
        }), 400

    if playlist == "generated":
        meta = load_generated_music_metadata()
    elif playlist == "library":
        meta = load_music_metadata()
    else:
        return jsonify({
            "ok": False,
            "error": {"code": "VALIDATION_FAILED", "message": f"Unknown playlist '{playlist}'"},
        }), 400

    # The metadata files are flat {filename: {...}}. There's no concept of a
    # named in-file playlist yet — the social spec says we should look for
    # songs whose metadata mentions the playlist name. For MVP, we treat the
    # playlist arg as "all songs in this directory" if `name` matches a tag,
    # otherwise we send all songs in the dir. AI-Radio dedupes by sourceHash.
    matching_files = []
    name_lower = (name or "").strip().lower()
    for fname, entry in (meta or {}).items():
        playlist_tags = entry.get("playlists") or []
        if isinstance(playlist_tags, str):
            playlist_tags = [playlist_tags]
        tag_match = any(
            isinstance(t, str) and t.lower() == name_lower for t in playlist_tags
        )
        if tag_match:
            matching_files.append(fname)
    if not matching_files:
        # Fallback: the whole directory.
        base_dir = GENERATED_MUSIC_DIR if playlist == "generated" else MUSIC_DIR
        for f in base_dir.iterdir():
            if f.is_file() and f.suffix.lower() in {".mp3", ".wav", ".ogg", ".m4a", ".webm"}:
                matching_files.append(f.name)

    print(f"📻 push-playlist: '{name}' ({playlist}) — {len(matching_files)} song(s)")

    # 1. Create the playlist on AI-Radio first.
    create_payload = {
        "name": name,
        "description": description,
        "source": "ovu-library" if playlist == "library" else "ovu-generated",
    }
    create_result = _airadio_call("POST", "/api/agent/push-playlist", json=create_payload)
    if not create_result["ok"]:
        return _bridge_response(create_result)
    playlist_data = create_result.get("data") or {}
    playlist_id = playlist_data.get("id") or playlist_data.get("playlistId")

    # 2. Push each song inline. Track per-song results so the caller sees
    #    which ones failed without aborting the whole batch.
    pushed = []
    failed = []
    for fname in matching_files:
        local_path, song_meta = _resolve_local_song(fname, playlist)
        if local_path is None:
            failed.append({"filename": fname, "error": "NOT_FOUND"})
            continue
        fields = {
            "title": (song_meta or {}).get("title") or local_path.stem,
            "source": "ovu-library" if playlist == "library" else "ovu-generated",
            "playlist": playlist,
            "playlistId": str(playlist_id) if playlist_id else "",
            "playlistName": name,
        }
        for src_key, dst_key in (
            ("artist", "artist"),
            ("genre", "genre"),
            ("description", "description"),
            ("duration_seconds", "duration"),
            ("suno_id", "sunoId"),
        ):
            if song_meta and song_meta.get(src_key) is not None:
                fields[dst_key] = str(song_meta[src_key])
        song_result = _stream_song(local_path, fields)
        if song_result["ok"]:
            sd = song_result.get("data") or {}
            pushed.append({
                "filename": fname,
                "songId": sd.get("songId") or sd.get("id"),
                "url": sd.get("url"),
            })
        else:
            failed.append({
                "filename": fname,
                "error": (song_result.get("error") or {}).get("code", "PUSH_FAILED"),
                "message": (song_result.get("error") or {}).get("message"),
            })

    return jsonify({
        "ok": True,
        "playlist": playlist_data,
        "pushed_count": len(pushed),
        "failed_count": len(failed),
        "pushed": pushed,
        "failed": failed,
    }), 200


@airadio_bp.route("/api/airadio/set-image", methods=["POST"])
def set_image():
    """
    Update an avatar / banner / song cover / playlist cover on AI-Radio.

    Body: { "target": "avatar"|"banner"|"song_cover"|"playlist_cover",
            "target_id": optional, "path": "/uploads/..." }
    """
    if not _bridge_configured():
        return _bridge_not_configured_response()

    body = request.get_json(silent=True) or {}
    target = body.get("target")
    target_id = body.get("target_id", "")
    raw_path = body.get("path", "")

    if target not in ("avatar", "banner", "song_cover", "playlist_cover"):
        return jsonify({
            "ok": False,
            "error": {
                "code": "VALIDATION_FAILED",
                "message": "target must be one of avatar, banner, song_cover, playlist_cover",
            },
        }), 400

    local_path = _resolve_image_path(raw_path)
    if local_path is None:
        return jsonify({
            "ok": False,
            "error": {
                "code": "VALIDATION_FAILED",
                "message": (
                    "Image path must point to an existing file under one of the "
                    "whitelisted dirs (uploads, faces, known_faces, generated_music, 1temp). "
                    "No '..' or absolute paths outside the whitelist."
                ),
            },
        }), 400

    if target in ("song_cover", "playlist_cover") and not target_id:
        return jsonify({
            "ok": False,
            "error": {
                "code": "VALIDATION_FAILED",
                "message": f"target_id is required when target='{target}'",
            },
        }), 400

    fields = {"target": target}
    if target_id:
        fields["targetId"] = str(target_id)

    print(f"📻 set-image: target={target} id={target_id or '-'} file={local_path.name}")
    result = _stream_image(local_path, fields)
    return _bridge_response(result)


@airadio_bp.route("/api/airadio/resolve", methods=["GET"])
def resolve():
    """
    Fuzzy-resolve a song or playlist query → { id, url, title, artist }.

    Query params: type=song|playlist, query=<text>
    """
    if not _bridge_configured():
        return _bridge_not_configured_response()

    rtype = request.args.get("type", "song")
    query = request.args.get("query", "")
    if rtype not in ("song", "playlist"):
        return jsonify({
            "ok": False,
            "error": {"code": "VALIDATION_FAILED", "message": "type must be 'song' or 'playlist'"},
        }), 400
    if not query:
        return jsonify({
            "ok": False,
            "error": {"code": "VALIDATION_FAILED", "message": "Missing 'query' param"},
        }), 400

    print(f"📻 resolve: type={rtype} query='{query}'")
    result = _airadio_call(
        "GET",
        "/api/agent/resolve",
        params={"type": rtype, "query": query},
    )
    return _bridge_response(result)


@airadio_bp.route("/api/airadio/play", methods=["POST"])
def play():
    """
    Resolve a song / playlist if needed, then return its URL+metadata.

    The frontend music player handles actual playback — this endpoint is a
    helper for the voice tag parser that needs `{ url, title, ... }`.

    Body: { "type": "song"|"playlist", "id": "..."  OR  "query": "..." }
    """
    if not _bridge_configured():
        return _bridge_not_configured_response()

    body = request.get_json(silent=True) or {}
    rtype = body.get("type", "song")
    rid = body.get("id")
    query = body.get("query")

    if rtype not in ("song", "playlist"):
        return jsonify({
            "ok": False,
            "error": {"code": "VALIDATION_FAILED", "message": "type must be 'song' or 'playlist'"},
        }), 400
    if not rid and not query:
        return jsonify({
            "ok": False,
            "error": {"code": "VALIDATION_FAILED", "message": "Provide either 'id' or 'query'"},
        }), 400

    # Resolve a query → id first if necessary.
    if not rid:
        print(f"📻 play: resolving '{query}' (type={rtype})")
        resolved = _airadio_call(
            "GET",
            "/api/agent/resolve",
            params={"type": rtype, "query": query},
        )
        if not resolved["ok"]:
            return _bridge_response(resolved)
        rdata = resolved.get("data") or {}
        rid = rdata.get("id")
        if not rid:
            return jsonify({
                "ok": False,
                "error": {"code": "NOT_FOUND", "message": f"No {rtype} matching '{query}'"},
            }), 404

    print(f"📻 play: type={rtype} id={rid}")
    # Ask AI-Radio for the canonical URL for that ID.
    result = _airadio_call(
        "GET",
        "/api/agent/resolve",
        params={"type": rtype, "id": rid},
    )
    if not result["ok"]:
        return _bridge_response(result)
    data = result.get("data") or {}

    return jsonify({
        "ok": True,
        "type": rtype,
        "id": data.get("id") or rid,
        "url": data.get("url"),
        "title": data.get("title"),
        "artist": data.get("artist"),
        "data": data,
    }), 200


@airadio_bp.route("/api/airadio/inbox", methods=["GET"])
def inbox():
    """Songs friends have sent to the current user (unread + recent)."""
    if not _bridge_configured():
        return _bridge_not_configured_response()
    print("📻 inbox: fetching")
    result = _airadio_call("GET", "/api/agent/inbox")
    return _bridge_response(result)


@airadio_bp.route("/api/airadio/send-to-friend", methods=["POST"])
def send_to_friend():
    """
    Send a song to a friend.

    Body: { "song_id": optional, "song_title": optional,
            "receiver_handle": "@nick", "note": optional }
    """
    if not _bridge_configured():
        return _bridge_not_configured_response()

    body = request.get_json(silent=True) or {}
    song_id = body.get("song_id")
    song_title = body.get("song_title")
    receiver = body.get("receiver_handle")
    note = body.get("note", "")

    if not receiver:
        return jsonify({
            "ok": False,
            "error": {"code": "VALIDATION_FAILED", "message": "Missing 'receiver_handle'"},
        }), 400
    if not song_id and not song_title:
        return jsonify({
            "ok": False,
            "error": {"code": "VALIDATION_FAILED", "message": "Provide 'song_id' or 'song_title'"},
        }), 400

    if not song_id:
        print(f"📻 send-to-friend: resolving song '{song_title}'")
        resolved = _airadio_call(
            "GET",
            "/api/agent/resolve",
            params={"type": "song", "query": song_title},
        )
        if not resolved["ok"]:
            return _bridge_response(resolved)
        song_id = (resolved.get("data") or {}).get("id")
        if not song_id:
            return jsonify({
                "ok": False,
                "error": {"code": "NOT_FOUND", "message": f"No song matching '{song_title}'"},
            }), 404

    print(f"📻 send-to-friend: song={song_id} receiver={receiver}")
    result = _airadio_call(
        "POST",
        "/api/agent/send-to-friend",
        json={"songId": song_id, "receiverHandle": receiver, "note": note},
    )
    return _bridge_response(result)


@airadio_bp.route("/api/airadio/vote", methods=["POST"])
def vote():
    """
    Vote on a song.

    Body: { "song_id": optional, "song_title": optional, "value": 1|-1|0 }
    """
    if not _bridge_configured():
        return _bridge_not_configured_response()

    body = request.get_json(silent=True) or {}
    song_id = body.get("song_id")
    song_title = body.get("song_title")
    value = body.get("value")

    if value not in (1, -1, 0):
        return jsonify({
            "ok": False,
            "error": {"code": "VALIDATION_FAILED", "message": "'value' must be 1, -1, or 0"},
        }), 400
    if not song_id and not song_title:
        return jsonify({
            "ok": False,
            "error": {"code": "VALIDATION_FAILED", "message": "Provide 'song_id' or 'song_title'"},
        }), 400

    if not song_id:
        print(f"📻 vote: resolving song '{song_title}'")
        resolved = _airadio_call(
            "GET",
            "/api/agent/resolve",
            params={"type": "song", "query": song_title},
        )
        if not resolved["ok"]:
            return _bridge_response(resolved)
        song_id = (resolved.get("data") or {}).get("id")
        if not song_id:
            return jsonify({
                "ok": False,
                "error": {"code": "NOT_FOUND", "message": f"No song matching '{song_title}'"},
            }), 404

    print(f"📻 vote: song={song_id} value={value}")
    result = _airadio_call("POST", "/api/agent/vote", json={"songId": song_id, "value": value})
    return _bridge_response(result)


# ---------------------------------------------------------------------------
# Friend management — pure pass-through
# ---------------------------------------------------------------------------


def _friend_passthrough(action_path: str):
    if not _bridge_configured():
        return _bridge_not_configured_response()
    body = request.get_json(silent=True) or {}
    handle = body.get("handle")
    if not handle:
        return jsonify({
            "ok": False,
            "error": {"code": "VALIDATION_FAILED", "message": "Missing 'handle'"},
        }), 400
    print(f"📻 {action_path}: handle={handle}")
    result = _airadio_call("POST", action_path, json={"handle": handle})
    return _bridge_response(result)


@airadio_bp.route("/api/airadio/friend-request", methods=["POST"])
def friend_request():
    return _friend_passthrough("/api/agent/friend-request")


@airadio_bp.route("/api/airadio/friend-accept", methods=["POST"])
def friend_accept():
    return _friend_passthrough("/api/agent/friend-accept")


@airadio_bp.route("/api/airadio/friend-decline", methods=["POST"])
def friend_decline():
    return _friend_passthrough("/api/agent/friend-decline")


# ---------------------------------------------------------------------------
# Library
# ---------------------------------------------------------------------------


@airadio_bp.route("/api/airadio/library", methods=["GET"])
def library():
    """Current user's library on AI-Radio (own songs + playlists)."""
    if not _bridge_configured():
        return _bridge_not_configured_response()
    print("📻 library: fetching")
    result = _airadio_call("GET", "/api/agent/library")
    return _bridge_response(result)


# ---------------------------------------------------------------------------
# Full catalog API (doc 22 — additive, cross-user)
# ---------------------------------------------------------------------------


# Query params we forward to /api/agent/catalog. Anything else is dropped.
_CATALOG_PASSTHROUGH_PARAMS = ("q", "genre", "artist", "sort", "cursor", "limit")


@airadio_bp.route("/api/airadio/catalog", methods=["GET"])
def catalog():
    """
    Platform-wide public song catalog search.

    Query params:
      q, genre, artist, sort=new|trending|top_week|top_all|plays,
      cursor, limit (<=100, default 24).

    Returns {items: [...], nextCursor}. Each item has a signed `streamUrl`
    valid for 15 minutes that can be fed directly to the OVU music player
    — no Clerk session needed.
    """
    if not _bridge_configured():
        return _bridge_not_configured_response()

    params = {
        k: request.args.get(k)
        for k in _CATALOG_PASSTHROUGH_PARAMS
        if request.args.get(k) is not None
    }
    print(f"📻 catalog: {params}")
    result = _airadio_call("GET", "/api/agent/catalog", params=params or None)
    return _bridge_response(result)


@airadio_bp.route("/api/airadio/catalog/<song_id>", methods=["GET"])
def catalog_detail(song_id):
    """Single song detail (catalog shape + viewer flags: liked, voted, saved)."""
    if not _bridge_configured():
        return _bridge_not_configured_response()
    if not song_id:
        return jsonify({
            "ok": False,
            "error": {"code": "VALIDATION_FAILED", "message": "Missing song id"},
        }), 400
    print(f"📻 catalog/{song_id}")
    result = _airadio_call("GET", f"/api/agent/catalog/{song_id}")
    return _bridge_response(result)


@airadio_bp.route("/api/airadio/u/<username>/songs", methods=["GET"])
def user_songs(username):
    """Paginated public songs by @<username> (all songs if it's the caller)."""
    if not _bridge_configured():
        return _bridge_not_configured_response()
    if not username:
        return jsonify({
            "ok": False,
            "error": {"code": "VALIDATION_FAILED", "message": "Missing username"},
        }), 400
    handle = username.lstrip("@")
    params = {}
    for k in ("cursor", "limit"):
        v = request.args.get(k)
        if v is not None:
            params[k] = v
    print(f"📻 u/{handle}/songs: {params}")
    result = _airadio_call(
        "GET",
        f"/api/agent/u/{handle}/songs",
        params=params or None,
    )
    return _bridge_response(result)


@airadio_bp.route("/api/airadio/song/<song_id>/stream-url", methods=["POST"])
def song_stream_url(song_id):
    """Issue a signed 15-min stream URL for the given song."""
    if not _bridge_configured():
        return _bridge_not_configured_response()
    if not song_id:
        return jsonify({
            "ok": False,
            "error": {"code": "VALIDATION_FAILED", "message": "Missing song id"},
        }), 400
    print(f"📻 stream-url: song={song_id}")
    result = _airadio_call("POST", f"/api/agent/song/{song_id}/stream-url")
    return _bridge_response(result)


@airadio_bp.route("/api/airadio/library/save", methods=["POST"])
def library_save():
    """
    Save another user's song to the caller's library.

    Body: { "song_id": "..." }  (accepts "songId" too for symmetry)
    """
    if not _bridge_configured():
        return _bridge_not_configured_response()
    body = request.get_json(silent=True) or {}
    song_id = body.get("song_id") or body.get("songId")
    if not song_id:
        return jsonify({
            "ok": False,
            "error": {"code": "VALIDATION_FAILED", "message": "Missing 'song_id'"},
        }), 400
    print(f"📻 library/save: song={song_id}")
    result = _airadio_call(
        "POST",
        "/api/agent/library/save",
        json={"songId": song_id},
    )
    return _bridge_response(result)


@airadio_bp.route("/api/airadio/playlist", methods=["POST"])
def playlist_create():
    """
    Create a new AI-Radio playlist owned by the caller.

    Body: { "name": "...", "description"?: "...", "is_public"?: bool }
    """
    if not _bridge_configured():
        return _bridge_not_configured_response()
    body = request.get_json(silent=True) or {}
    name = body.get("name")
    if not name:
        return jsonify({
            "ok": False,
            "error": {"code": "VALIDATION_FAILED", "message": "Missing 'name'"},
        }), 400
    payload = {"name": name}
    if body.get("description") is not None:
        payload["description"] = body.get("description")
    # Accept both is_public and isPublic from the caller.
    if "is_public" in body:
        payload["isPublic"] = bool(body.get("is_public"))
    elif "isPublic" in body:
        payload["isPublic"] = bool(body.get("isPublic"))
    print(f"📻 playlist/create: name={name}")
    result = _airadio_call("POST", "/api/agent/playlist", json=payload)
    return _bridge_response(result)


@airadio_bp.route("/api/airadio/playlist/<playlist_id>", methods=["GET"])
def playlist_read(playlist_id):
    """Read a playlist + ordered songs (each with a signed streamUrl)."""
    if not _bridge_configured():
        return _bridge_not_configured_response()
    if not playlist_id:
        return jsonify({
            "ok": False,
            "error": {"code": "VALIDATION_FAILED", "message": "Missing playlist id"},
        }), 400
    print(f"📻 playlist/{playlist_id}")
    result = _airadio_call("GET", f"/api/agent/playlist/{playlist_id}")
    return _bridge_response(result)


# ---------------------------------------------------------------------------
# Queue / Radio — voice-shaped shortcuts (doc 22+). Every endpoint returns
# {items, reason, nextCursor}. OVU can feed `items` straight into the music
# player. Each item has a 15-min signed streamUrl.
# ---------------------------------------------------------------------------


# Query params forwarded to every queue endpoint.
_QUEUE_PASSTHROUGH_PARAMS = (
    "mood",
    "genre",
    "freshness",
    "audience",
    "similarTo",
    "artist",
    "excludeHeard",
    "window",
    "q",
    "limit",
    "cursor",
    # bpmMin/bpmMax are rejected by the upstream today — forward so the
    # caller sees the VALIDATION_FAILED from AI-Radio unchanged.
    "bpmMin",
    "bpmMax",
)


def _queue_params():
    return {
        k: request.args.get(k)
        for k in _QUEUE_PASSTHROUGH_PARAMS
        if request.args.get(k) is not None
    }


def _queue_proxy(path):
    if not _bridge_configured():
        return _bridge_not_configured_response()
    params = _queue_params()
    print(f"📻 {path}: {params}")
    result = _airadio_call("GET", path, params=params or None)
    return _bridge_response(result)


@airadio_bp.route("/api/airadio/queue", methods=["GET"])
def queue_generic():
    """Generic queue resolver — all QueueParams are URL params."""
    return _queue_proxy("/api/agent/queue")


@airadio_bp.route("/api/airadio/queue/new", methods=["GET"])
def queue_new():
    return _queue_proxy("/api/agent/queue/new")


@airadio_bp.route("/api/airadio/queue/trending", methods=["GET"])
def queue_trending():
    return _queue_proxy("/api/agent/queue/trending")


@airadio_bp.route("/api/airadio/queue/top", methods=["GET"])
def queue_top():
    return _queue_proxy("/api/agent/queue/top")


@airadio_bp.route("/api/airadio/queue/random", methods=["GET"])
def queue_random():
    return _queue_proxy("/api/agent/queue/random")


@airadio_bp.route("/api/airadio/queue/friends", methods=["GET"])
def queue_friends():
    return _queue_proxy("/api/agent/queue/friends")


@airadio_bp.route("/api/airadio/queue/following", methods=["GET"])
def queue_following():
    return _queue_proxy("/api/agent/queue/following")


@airadio_bp.route("/api/airadio/queue/me", methods=["GET"])
def queue_me():
    return _queue_proxy("/api/agent/queue/me")


@airadio_bp.route("/api/airadio/queue/liked", methods=["GET"])
def queue_liked():
    return _queue_proxy("/api/agent/queue/liked")


@airadio_bp.route("/api/airadio/queue/unheard", methods=["GET"])
def queue_unheard():
    return _queue_proxy("/api/agent/queue/unheard")


@airadio_bp.route("/api/airadio/queue/genre/<slug>", methods=["GET"])
def queue_genre(slug):
    if not slug:
        return jsonify({
            "ok": False,
            "error": {"code": "VALIDATION_FAILED", "message": "Missing genre slug"},
        }), 400
    return _queue_proxy(f"/api/agent/queue/genre/{slug}")


@airadio_bp.route("/api/airadio/queue/mood/<mood>", methods=["GET"])
def queue_mood(mood):
    if not mood:
        return jsonify({
            "ok": False,
            "error": {"code": "VALIDATION_FAILED", "message": "Missing mood"},
        }), 400
    return _queue_proxy(f"/api/agent/queue/mood/{mood}")


@airadio_bp.route("/api/airadio/queue/artist/<username>", methods=["GET"])
def queue_artist(username):
    # Accept "@nick" as well as "nick"
    handle = (username or "").lstrip("@")
    if not handle:
        return jsonify({
            "ok": False,
            "error": {"code": "VALIDATION_FAILED", "message": "Missing username"},
        }), 400
    return _queue_proxy(f"/api/agent/queue/artist/{handle}")


@airadio_bp.route("/api/airadio/queue/similar/<song_id>", methods=["GET"])
def queue_similar(song_id):
    if not song_id:
        return jsonify({
            "ok": False,
            "error": {"code": "VALIDATION_FAILED", "message": "Missing song id"},
        }), 400
    return _queue_proxy(f"/api/agent/queue/similar/{song_id}")


@airadio_bp.route("/api/airadio/interpret", methods=["POST"])
def interpret():
    """Natural-language phrase → QueueParams + items."""
    if not _bridge_configured():
        return _bridge_not_configured_response()
    body = request.get_json(silent=True) or {}
    query = body.get("query")
    if not query:
        return jsonify({
            "ok": False,
            "error": {"code": "VALIDATION_FAILED", "message": "Missing 'query'"},
        }), 400
    print(f"📻 interpret: '{query}'")
    result = _airadio_call("POST", "/api/agent/interpret", json={"query": query})
    return _bridge_response(result)
